<?php return array (
  'october\\demo\\Plugin' => 'plugins\\october\\demo\\Plugin.php',
  'rainlab\\blog\\Plugin' => 'plugins\\rainlab\\blog\\Plugin.php',
  'rainlab\\forum\\Plugin' => 'plugins\\rainlab\\forum\\Plugin.php',
  'rainlab\\user\\Plugin' => 'plugins\\rainlab\\user\\Plugin.php',
  'RainLab\\Blog\\Classes\\TagProcessor' => 'plugins\\rainlab\\blog\\classes\\TagProcessor.php',
  'RainLab\\User\\Models\\User' => 'plugins\\rainlab\\user\\models\\User.php',
  'RainLab\\User\\Controllers\\Users' => 'plugins\\rainlab\\user\\controllers\\Users.php',
  'RainLab\\User\\Components\\Session' => 'plugins\\rainlab\\user\\components\\Session.php',
  'RainLab\\User\\Facades\\Auth' => 'plugins\\rainlab\\user\\facades\\Auth.php',
  'RainLab\\User\\Classes\\AuthManager' => 'plugins\\rainlab\\user\\classes\\AuthManager.php',
  'RainLab\\User\\Models\\Settings' => 'plugins\\rainlab\\user\\models\\Settings.php',
  'RainLab\\User\\Classes\\UserRedirector' => 'plugins\\rainlab\\user\\classes\\UserRedirector.php',
  'backend\\Controllers\\index' => 'modules\\backend\\controllers\\index.php',
  'backend\\Controllers\\auth' => 'modules\\backend\\controllers\\auth.php',
  'rainlab\\blog\\Controllers\\posts' => 'plugins\\rainlab\\blog\\controllers\\posts.php',
  'RainLab\\Blog\\Models\\PostImport' => 'plugins\\rainlab\\blog\\models\\PostImport.php',
  'RainLab\\Blog\\Models\\PostExport' => 'plugins\\rainlab\\blog\\models\\PostExport.php',
  'RainLab\\Blog\\Models\\Post' => 'plugins\\rainlab\\blog\\models\\Post.php',
  'RainLab\\Blog\\Models\\Category' => 'plugins\\rainlab\\blog\\models\\Category.php',
  'RainLab\\Blog\\FormWidgets\\BlogMarkdown' => 'plugins\\rainlab\\blog\\formwidgets\\BlogMarkdown.php',
  'system\\Controllers\\settings' => 'modules\\system\\controllers\\settings.php',
  'system\\Controllers\\mailtemplates' => 'modules\\system\\controllers\\mailtemplates.php',
);